#!/bin/bash

root=`git rev-parse --show-toplevel`
files=`git ls-files --full-name | grep -E "html$"`

cat << EOS
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
EOS

for file in $files
do
  path=$root/$file

  # デフォルト設定
  prefix="https://example.com"  # URL 前置詞
  function difftest () {  # ファイルの更新判定
    # $1 コミットのハッシュ
    # $2 ファイルパス
    return 0; # 無条件で「更新」判定
  }

  # 設定ファイルのパスを生成
  rcdirs=()
  rcdir=`dirname ${path}`
  while [ ${#rcdir} -ge ${#root} ];do
    rcdirs=(${rcdir}/.git-sitemaprc.sh "${rcdirs[@]}")
    rcdir=`cd ${rcdir}/.. && pwd`
  done

  # 設定読み込み
  for rcpath in ${rcdirs[@]}; do
    if [ -f ${rcpath} ]; then
      source ${rcpath}
    fi
  done

  # 更新回数の判定
  count=0
  hashes=(`git log --reverse --pretty=%H ${path}`)
  i=0
  for hash in ${hashes[@]}; do
    if [ $i -eq 0 ]; then
      # 最初のコミットは無条件で更新判定
      count=$(($count + 1))
    else
      # 更新判定
      if difftest ${hash} ${path}; then
        count=$(($count + 1))
      fi
    fi
    i=$(($i + 1))
  done
  if [ ${count} -eq 0 ]; then continue; fi

  # 作成日時と更新間隔の計算
  created=`git log --date=iso --pretty=format:"%ad" $path | tail -n 1`
  elapsed=$(((`date "+%s"` - `date "+%s" -d "$created"`)/$count))

  # <loc> の生成
  loc=`echo "${prefix}/${file}" | recode utf8..html`
  loc=${loc%index.html}

  # <changefreq> の生成
  if [ $elapsed -le $((60*60)) ];then
    changefreq="hourly"
  elif [ $elapsed -le $((60*60*24)) ];then
    changefreq="daily"
  elif [ $elapsed -le $((60*60*24*7)) ];then
    changefreq="weekly"
  elif [ $elapsed -le $((60*60*24*28)) ];then
    changefreq="monthly"
  else
    changefreq="yearly"
  fi

  # <lastmod> の生成
  # W3C Datetime: https://www.w3.org/TR/NOTE-datetime
  lastmod=$(date "+%Y-%m-%dT%H:%M:%S%:z" -d "`git log -1 --date=iso --pretty=format:"%ad" $path`")

  # <url> の登録
  echo "<url><loc>${loc}</loc><lastmod>${lastmod}</lastmod><changefreq>${changefreq}</changefreq></url>"
done

echo "</urlset>"
