#!/bin/bash

root=$(git rev-parse --show-toplevel)
files=$(git ls-files --full-name | grep -E "html$")

cat <<EOS
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
EOS

for file in $files; do
  path=$root/$file

  # デフォルト設定
  prefix="https://example.com" # URL 前置詞
  since="1970-01-01"           # コミット履歴の開始日付
  function difftest() { # ファイルの更新判定
    # $1 コミットのハッシュ
    # $2 ファイルパス
    return 0 # 無条件で「更新」判定
  }

  # 設定ファイルのパスを生成
  rcdirs=()
  rcdir=$(dirname ${path})
  while [ ${#rcdir} -ge ${#root} ]; do
    rcdirs=(${rcdir}/.git-sitemaprc.sh "${rcdirs[@]}")
    rcdir=$(cd ${rcdir}/.. && pwd)
  done

  # 設定読み込み
  for rcpath in ${rcdirs[@]}; do
    if [ -f ${rcpath} ]; then
      source ${rcpath}
    fi
  done

  # <loc> の生成
  loc=$(echo "${prefix}/${file}" | recode utf8..html)
  loc=${loc%index.html}

  # <lastmod> の生成
  # W3C Datetime: https://www.w3.org/TR/NOTE-datetime
  lastmod=$(date "+%Y-%m-%dT%H:%M:%S%:z" -d "$(git log -1 --date=iso --pretty=format:"%ad" $path)")

  # 更新回数の判定
  count=0
  first=$(git log --date=iso --pretty=%H $path | tail -n 1)
  hashes=($(git log --reverse --pretty=%H --since "${since}" ${path}))
  for hash in ${hashes[@]}; do
    if [ "${hash}" == "${first}" ]; then
      # 最初のコミットは無条件で更新判定
      count=$((count + 1))
    else
      # 更新判定
      if difftest ${hash} ${path}; then
        count=$((count + 1))
      fi
    fi
  done

  # <changefreq> の生成
  if [ ${count} -eq 0 ]; then
    changefreq="yearly"
  else
    created=$(git log --date=iso --pretty=format:"%ad" --since "${since}" $path | tail -n 1)
    elapsed=$((($(date "+%s") - $(date "+%s" -d "$created")) / count))

    if [ $elapsed -le $((60 * 60)) ]; then
      changefreq="hourly"
    elif [ $elapsed -le $((60 * 60 * 24)) ]; then
      changefreq="daily"
    elif [ $elapsed -le $((60 * 60 * 24 * 7)) ]; then
      changefreq="weekly"
    elif [ $elapsed -le $((60 * 60 * 24 * 28)) ]; then
      changefreq="monthly"
    else
      changefreq="yearly"
    fi
  fi

  # <url> の登録
  echo "  <url>"
  echo "    <loc>${loc}</loc>"
  echo "    <lastmod>${lastmod}</lastmod>"
  echo "    <changefreq>${changefreq}</changefreq>"
  echo "  </url>"
done

echo "</urlset>"
